### ISSUE TITLE
Operations (+) and (-) in the natural set are not closed

### ISSUE THREAD

**Issue by xfarrow** [Yet-Zio/yetCalc#10]
Operations (+) and (-) in the natural set give a result in the set of real numbers.

For example, 2+2=4, but the app gives 4.0 as result.

**Comment by Yet-Zio** [comment]
The reason you are seeing simple expressions return a real number is that the library [mXparser](https://mathparser.org) returns a double due to its rounding settings to solve issues like [these](https://mathparser.org/mxparser-tutorial/smart-rounding-settings/). Also a mistake from my side, thought I could adjust mXparser's Almost Int Rounding feature to solve the issue at the time of release.

However, I have already figured out a solution to this and the issue will be fixed in the next update ASAP. Sorry for any inconvenience.

**Comment by Yet-Zio** [comment]
Issue fixed as of #12
