### ISSUE TITLE
Weird Button Shape

### ISSUE THREAD

**Issue by LovecraftianGodsKiller** [Yet-Zio/yetCalc#11]
There's a problem where the shapes of the buttons for the calculator are shaped correctly. I have a Samsung Galaxy Z Flip 4 and my guess is that it's just a scaling issue seeing as the phone is much taller than most other phones out there.
![Screenshot_20230104_080841_yetCalc](https://user-images.githubusercontent.com/82244192/210598828-1eb62d61-5dcd-402a-9ebd-d8a1281be3e2.jpg)

**Comment by Yet-Zio** [comment]
Hello @LovecraftianGodsKiller, yes this is a scaling issue as I never tested it on the size scale of a foldable. Will look into this once I get enough time, probably a separate layout for screen sizes such as this. Sorry for the inconvenience caused :(

**Comment by Baker0o7** [comment]
Hi sir thanks I kindly suggest if you make the shape circular instead of oval shape

**Comment by Yet-Zio** [comment]
Hi @Baker0o7, thanks for the suggestion, however this is a scaling issue. I need to make a separate layout or drawables for supporting taller screen sizes like that of a foldable.

**Comment by moriel5** [comment]
A Razer Phone 2 here, so not a foldable, just a standard 9:16 aspect ratio screen with no notch, and the scaling is wrong here as well, with the buttons looking squashed.

**Comment by dannyhand** [comment]
Same with my Galaxy Note 20 Ultra. I keep my phone at 513dp minimum width (Settings > Developer Options > Drawing > Minimum Width) if that helps.

**Comment by Yet-Zio** [comment]
@moriel5 and @dannyhand thank you for your reports.

@moriel5 judging by your phone size(5.7 inches), do the bottom buttons get cut off or does it look squashed similar to the first case? Would you be willing to send a screenshot if possible?

@dannyhand for you I think its a case of really tall screens, I think its 6.9in for you. which will be fixed once I release a layout with support for larger screens.

**Comment by moriel5** [comment]
@Yet-Zio I am sorry I had forgotten to mention this crucial information, however my display resolution is currently set to 1080p, with a custom DPI of 300 and minimum smallest width of 576dp, in order to make things closer to the default 1440p resolution, until I find time to replace the ROM and use this device as a daily driver.

It's similar to, yet different from the first example, since nothing is cut off, however the spacing between the keys remains normal, it is only the buttons that are compressed.

Here is the screenshot: ![](https://i.imgur.com/jakXhhQ.png).

**Comment by Yet-Zio** [comment]
Fixed with major version upgrade #147
