### ISSUE TITLE
System buttons bar have white on white buttons + buttons cutoff at bottom[possibly screen size]

### ISSUE THREAD

**Issue by Porkepix** [Yet-Zio/yetCalc#113]
System buttons bar have white on white buttons which are barely visible.
Device runs Android Oreo (8.0) stock. See screenshot below.

<details>
<summary>
Screenshot
</summary>

![Screenshot_20240313-120427](https://github.com/Yet-Zio/yetCalc/assets/709500/60be3376-12da-45e4-a057-96839114c264)

</details>

**Comment by Yet-Zio** [comment]
@Porkepix what's your screen size?

**Comment by Yet-Zio** [comment]
Hmm
![Screenshot_20240313-182626](https://github.com/Yet-Zio/yetCalc/assets/38321498/8c96e9f7-3f98-4c35-ada9-2ab6c7a62757)
In this device, the light theme doesn't have that issue, on Android 11. But that doesn't matter, I haven't done anything to modify the navigator bar button color itself only the background color, don't know why your device interprets it that way.

Also you made another issue concerning buttons cutting off as your navigation bar takes space. This is apparently due to screen size as I haven't optimized it for lower sizes, I might implement a scroll later.

**Comment by Yet-Zio** [comment]
@Porkepix About your navigation bar buttons getting white with the background, that's really weird, this is unrelated to screen size or theme and I have never seen that occuring.
