### ISSUE TITLE
Odd error in basic subtraction. 

### ISSUE THREAD

**Issue by ConorIA** [Yet-Zio/yetCalc#146]
Not sure why, but yetCalc returns 0.9(repeating) in some instances when it should return the whole digit.

![Screenshot_20241108-203924_yetCalc](https://github.com/user-attachments/assets/460fd1b0-70f2-46c9-9eb6-0c357a984003)

**Comment by Yet-Zio** [comment]
Please go to settings and enable Canonical Rounding. It will then be solved. The reason is that by default Canonical Rounding is turned off since there are some math functions I have provided that might need to work on even with a large precision, in that case canonical rounding will prove troublesome since it will round to a whole number.

But for simple operations like these, Canonical rounding can be turned on.

Do you wish to enable Canonical Rounding by default in a later release? because Im reworking on the calculator.
