### ISSUE TITLE
Network permission removal in seperate release?

### ISSUE THREAD

**Issue by dhammel** [Yet-Zio/yetCalc#27]
Hello,

so far yetCalc seems to be more stable and feature packed than other calculators i've seen.

My only concern is the network permission, if its not too much of an extra maintenance burden, could you create a 2nd release apk that has network permission removed and just have the features that require it disabled or removed?

**Comment by ExperiencersInternational** [comment]
Couldn't you just disable the app from using the network in Settings?

![Screenshot_2023-01-14-22-34-32-817_com miui securitycenter](https://user-images.githubusercontent.com/56035537/212500068-82445f62-8be5-4119-8b53-9fa2453fdfe5.jpg)

**Comment by dhammel** [comment]
@ExperiencersInternational My phone (Pixel 6) runs stock AOSP, no it doesn't have such an option. I could use a firewall, like netguard, but there are times where during restart it takes time for the firewall to startup. Though if app doesn't need network, it shouldn't have such a permission.

Since app is open-source I suppose I could do it myself, its just something that I would have to do each time an update is released.

**Comment by ExperiencersInternational** [comment]
@dhammel tbh I just don't see why as a developer you would go out just to remove the internet components

I haven't used stock AOSP since around 2017, so I really can't say much.

**Comment by dhammel** [comment]
@ExperiencersInternational Apps that don't need internet for its functionality shouldn't have them, for privacy reasons. As far as I see, currency conversion is the only feature needing internet but i have no need for currency conversion. Some may, which is why I suggested a seperate apk, rather than removing it outright.

**Comment by Yet-Zio** [comment]
@dhammel I understand your concern. However, the currency conversion tab only sends an API request to [exchangeratehost](https://exchangerate.host/#/) if the field values are not empty. Also, before doing that it checks if you have a stable internet connection. This way it never sends any data outside without your actions.

If that is not satisfiable, then you can select any other tab for example 'Length'. Since 'Use Recent Tab' setting is enabled by default, it will never load the currency tab. Note that the currency tab would still get added to the tabs tho.

Removing the internet permission entirely would be to remove the currency tab itself, that would not be hard but maintaining every release might. Do you still want a separate release?

**Comment by dhammel** [comment]
@Yet-Zio The main reason for removing a network permission is that when people would see that a calculator app has one, it would  be a concern, unless the user reads over the source code himself it would come down to trust.

As I said though, if its too much work to maintain every releaee then i wouldn't bother.

**Comment by Yet-Zio** [comment]
@dhammel that is true, but if I did remove network permission and currency conversion, then I would need to make sure everything works when I make changes to [Unit Conversion Activity and related settings](https://github.com/Yet-Zio/yetCalc/blob/main/app/src/main/java/yetzio/yetcalc/views/UnitConvActivity.kt) and confirm that there are no issues on both sides, this would be tiresome as I already don't get time nowadays due to college and other things.

Maybe I should instead add an intro tour later with doubts on faq.
