### ISSUE TITLE
App can't add/subtract percentages properly

### ISSUE THREAD

**Issue by ExperiencersInternational** [Yet-Zio/yetCalc#28]
So, I really wanted to use this to replace the stock Xiaomi calculator, which I had replaced with the Google calculator, but the app cannot even calculate adding or subtracting percentages properly (I'm guessing it's just calculating the percentage in 1?).

![Screenshot_2023-01-14-22-27-56-147_yetzio yetcalc](https://user-images.githubusercontent.com/56035537/212499870-60516100-eca7-42ad-9624-15ad942ddce8.jpg)
![Screenshot_2023-01-14-22-27-47-340_yetzio yetcalc](https://user-images.githubusercontent.com/56035537/212499873-fab8c480-8f9e-438e-a7b8-739100872df6.jpg)

**Comment by Yet-Zio** [comment]
Hi @ExperiencersInternational thanks for the report. First I thought this might be an issue because of the updates I did to the calculator component. But, seems like this is how mXparser, the library that the calculator mode uses handles percentages. Yea it calculates the percentage in 1. Funny enough, I didn't notice this. I will probably have to ask the library author for this one. Sorry for any inconvenience.

**Comment by Yet-Zio** [comment]
Hello @ExperiencersInternational, I have received a reply from mXparser's author. mXparser takes a more correct math perspective for the syntax similar to excel. For your case 5-20% can be calculated simply by 5-20%*5 or 5+20%*5. Like if you do 2% * 100, it will be 2% of 100. By default the percentage operator calculates in 1. I hope that solves your issue.
