### ISSUE TITLE
PayPal not accepting transactions 

### ISSUE THREAD

**Issue by antenore** [Yet-Zio/yetCalc#37]
Thanks for yetCalc!

I wanted to donate through PayPal but it says you cannot accept payments at the moment.

I hope you will solve soon the issues.

PayPal is a bad beast!

**Comment by Yet-Zio** [comment]
@antenore Ah I thought this would occur due to some restrictions PayPal has for international transactions, that would require me to upgrade to a business account. For that I need a PAN card issued by my country (India). 

Im only 19, I can get it but don't get the time due to college and exams. When I get and link it, the issue will probably be solved.

This is why I linked patreon but that's more like monthly. Anyway, @antenore thanks for considering to donate. Hope yetCalc helps you with your calculations :)

**Comment by antenore** [comment]
I'll find a way, no problem.
But I get as well international donations through PayPal with a normal account.

**Comment by antenore** [comment]
In Lo-fi it's the same

> Oops, that didn't work
This account isn't enabled to make cross border transactions. You can enable your account at https://dashboard.stripe.com/settings/update

**Comment by Yet-Zio** [comment]
Hmm, I added the identity details such as PAN, Paypal seems to have this issue and I have contacted them. Stripe does actually verify bank, PAN and other details but responds with "cannot make cross border transactions." when I try to create a payment link or something similar, they give that link too but there's nothing to update lol, I added almost everything. They don't even mention clearly why this happens in the docs.

**Comment by antenore** [comment]
I don't know if it'll work, if you're based in India, I know there're some data and money transfer restrictions.
Maybe Bitcoin or other cryptos?

**Comment by Yet-Zio** [comment]
Hi, I have added buymeacoffee link for donations and updated the [Donate.md](https://github.com/Yet-Zio/yetCalc/blob/main/DONATE.md) page, so now you can even donate through UPI services like Google Pay.

**Comment by antenore** [comment]
Cool! That works!!!
Just done right now and twitted about it

**Comment by Yet-Zio** [comment]
Thank you so much for your donation. :)
