### ISSUE TITLE
percentage(concern about intended behavior)

### ISSUE THREAD

**Issue by Wjxfi** [Yet-Zio/yetCalc#41]
opencalc vs yetcalc
![312148.jpg](https://user-images.githubusercontent.com/113500363/218331519-e22ec5b9-5c1f-4113-a1c0-138db1706b24.jpg)
![312154.jpg](https://user-images.githubusercontent.com/113500363/218331706-4542801f-189a-44f9-b85a-372eda2dece5.jpg)
![312157.jpg](https://user-images.githubusercontent.com/113500363/218331772-bb6fc3c2-4713-4853-821a-d0248ab9e65d.jpg)
![312160.jpg](https://user-images.githubusercontent.com/113500363/218331864-04106070-0188-4078-9635-78fdf8bffaa1.jpg)

**Comment by Yet-Zio** [comment]
Hello @Wjxfi , yetCalc calculates percentages in a more traditional, mathematical way. To get the same result as open calc, use % operator with asterisk(*). For example: 1000-90%*1000

**Comment by Yet-Zio** [comment]
I will mention this issue in help so that more users can get help. By default percentage operator calculates in 1

**Comment by Yet-Zio** [comment]
Sorry @Wjxfi , by asterisk I meant the multiplication operator. Hope this helps. I have just updated the help as well

**Comment by Yet-Zio** [comment]
@Wjxfi sure I was thinking to add that but couldn't figure out how since the calculations are handled directly by mXparser. I will add it surely when I figure it out.

**Comment by Yet-Zio** [comment]
@Wjxfi ofc its not gonna work for division. You are dividing 150/5% , which I don't know how open calc's implementation is, percentage really varies even in google, but its quite different. Whereas in yetcalc you are dividing 150/5%*150, that means 5% of 150 or 150/5%/150, that means 5% by 150. The question here is how is open calc handling it, it appears wrong to me. For division you can do basically: 150/5% which would work. No need for multiplication if that's your doubt. Hope it helps. Feel free to ask anything. I am having exams tmrw and about to sleep, that's why there was a delay in conversations.

**Comment by Yet-Zio** [comment]
@Wjxfi I have looked at the source code, particularly at Expression.kt , it does not explicitly state how it handles every operator. Also the result is wrong, percentages are not handled like that(mathematically). You can enter the same expression in any other calculator other than open calc, for example: 150/5% , it should give 3000. Percentages are calculated in 1 by default. So the expression: 150/5% will give you the result(you don't need to multiply), here yetCalc is correct.

**Comment by Yet-Zio** [comment]
Closing as this is hopefully solved

**Comment by Yet-Zio** [comment]
@Wjxfi, I was talking about how division operators are handled through percentages. Your screenshots provided had this expression: 150/5%/150. Now why would you divide a percentage or multiply it? You only do that for adding and subtracting.

It should be just 150/5% which is 3000. Please check with any other calculator as well. Result in openCalc is wrong.
