### ISSUE TITLE
Currency converter improvements

### ISSUE THREAD

**Issue by yonoff** [Yet-Zio/yetCalc#46]
Please add an option to remember last used currency in currency converter tab. 
I would also like to be able to create favorites for currencies and be able to choose from them.  
Or at least a search, because it is very inconvenient to search for a currency in a long list.

**Comment by Yet-Zio** [comment]
@yonoff Sorry for the inconvenience caused and thanks for the suggestion, I will probably make it so that the converter remembers the last used currency since its already a long list with all those abbreviations. Search on a spinner(list) is useful as well. Hmm about favourites, I will look into that :).

**Comment by Yet-Zio** [comment]
Unit Pins, Search, groups setting, added with #147
