### ISSUE TITLE
Missing icon in older android

### ISSUE THREAD

**Issue by Tarek-Hasan** [Yet-Zio/yetCalc#49]
In android 6 app icon is missing and shows a generic app icon.

**Comment by Yet-Zio** [comment]
@Tarek-Hasan Thanks for your report. I understand the issue, this is probably happening because older versions(Android 7.0 and below) may not support the adaptive and legacy icons generated by Android Studio. This will be fixed in the upcoming update :). 
Also I would recommend you update your android device as well because 6.0(Marshmallow) is 7 years old.

**Comment by Yet-Zio** [comment]
Fixed as of #53
