### ISSUE TITLE
I can not read numbers

### ISSUE THREAD

**Issue by heberjeur** [Yet-Zio/yetCalc#51]
When I calculate for example 13000/30, I see that
![Screenshot_20230318-085331_yetCalc](https://user-images.githubusercontent.com/11852634/226092957-d37541f2-8d39-49d4-b5df-86cae0a64089.jpg)

I can not read the first numbers, 
![Screenshot_20230318-085415_yetCalc](https://user-images.githubusercontent.com/11852634/226093031-491d8ef4-03a3-44d9-8e21-887546e59793.jpg)

I suggest to specify the decimal number like that

![Screenshot_20230318-085756_Unitto](https://user-images.githubusercontent.com/11852634/226093207-097a9d44-e8ed-41ef-9e2a-3ce8d97b77a3.jpg)

**Comment by Yet-Zio** [comment]
Hmm, I think you mean not all numbers are present since the result is larger and you need to scroll for that. For that I will probably provide a font setting in the near future. See issue #48 

But I do not understand that you show a screenshot of precision setting which has nothing to do with it.

Anyway, thanks for your report @heberjeur

**Comment by heberjeur** [comment]
Yes, sorry for my bad English

**Comment by Yet-Zio** [comment]
Results are left aligned as of v1.1.2 . Can be changed in settings as well. #107
