### ISSUE TITLE
Volume conversion fails from units like Tablespoons(US), Teaspoons(UK) -  Possible issue from 1.0.6

### ISSUE THREAD

**Issue by Andoriax** [Yet-Zio/yetCalc#52]
The conversion will not automatically compute, nor upon confirmation of the entry and selection via the bottom [Enter] button.

Further irony, the results field (the second measurement field) oddly seems to request manual insertion of the answer — as the cursor continues to bat it it's eye in hopes for an entry.

Congratulations on the UI, though.

![IMG_20230407_100854](https://user-images.githubusercontent.com/123551386/230649467-bc2b8d51-6c67-4d61-b803-bb08caa3fa70.jpg)

**Comment by Yet-Zio** [comment]
Hello @Andoriax, yes **volume conversion** does fail while converting to or from units like teaspoons and tablespoons since 1.0.6 after I fixed another issue regarding cups, quarts, etc and I did not get the time to review all the units of every section at that time.

> Further irony, the results field (the second measurement field) oddly seems to request manual insertion of the answer — as the cursor continues to bat it it's eye in hopes for an entry.

First thing, you can convert to and from either of those fields and that means it accepts an input. It does not request or force you to write the answer or so, that's your choice. When it fails, ofcourse it won't show any result or would be wrong.

Well, thanks for the report. I will be working on it when I get time and by the way the next time you create an issue, please provide an accurate title and description with some deceny.

**Comment by Andoriax** [comment]
You're on it!
My apologies, and will do!

**Comment by Yet-Zio** [comment]
Fixed as of #53
