### ISSUE TITLE
MathParser.org-mXparser v5.0 and later is not FOSS

### ISSUE THREAD

**Issue by licaon-kter** [Yet-Zio/yetCalc#98]
ref: https://github.com/mariuszgromada/MathParser.org-mXparser/blob/v.5.0.0/LICENSE.txt

ref: https://gitlab.com/fdroid/fdroiddata/-/issues/3141

ref: https://github.com/Yet-Zio/yetCalc/blob/1.0.4/app/build.gradle#L50

/LE: this means that at the moment no app version can be included in F-Droid

**Comment by licaon-kter** [comment]
And more so, can you point out which FOSS (OSI and/or FSF) license is used exactly? https://spdx.org/licenses/

**Comment by Yet-Zio** [comment]
I think the non commercial one uses or is similar to the BSD 2-Clause "Simplified" License.

**Comment by licaon-kter** [comment]
Similar indeed, but... adds its incompatible rules on top :(

**Comment by licaon-kter** [comment]
fyi :( https://gitlab.com/fdroid/fdroiddata/-/commit/663b241ba4c5899675969ea60c1f402bd92fa7d3

**Comment by linsui** [comment]
The license is not very clear but looks not compatible with FOSS.

> NON-COMMERCIAL USE means any use or activity where a fee is not charged
and the purpose is not the sale of a good or service, and the use or
activity is not intended to produce a profit. NON-COMMERCIAL USE examples:
> 1. Free Open-Source Software ("FOSS").
> 2. Non-commercial use in research, scholarly and education.

Dual license is allowed but one of the license should be a FOSS license.

**Comment by opk12** [comment]
I liked yetcalc :( I hope the apk's become FOSS in a future version. I see that the issue was closed and I'd make it explicit that F-droid is not being overly selective - the license is broken for me and anyone.

1. There is no such thing as a FOSS non-commercial (or research-only, educational-only) license.
   `Agreement` and `bound` are red flags.
   See the FSF [Four Freedoms](https://www.gnu.org/philosophy/free-sw.html.en#redistribute),  the [OSI definition](https://opensource.org/osd/) § 1 and 6, [Wikimedia Commons](https://commons.wikimedia.org/wiki/Commons:Licensing#Acceptable_licenses), [Wikipedia](https://en.wikipedia.org/wiki/Free_software#Business_model).
2. The license forbids using this calculator at work :(
3. The license forbids me to sell my phone with the app, which is a classic example of FOSS right.
4. Whatever `Non-commercial use examples: 1. FOSS` without a verb is supposed to mean, it does not mean that getting the lib as part of a FOSS app gives the right to commercial usage.
5. Permissive + commercial is generally not seen and I'd take it as a red flag in this case.
   Dual licensing usually means strong copyleft + permissive or weak copyleft.

**Comment by opk12** [comment]
Confirmation from the lib maintainer from [ticket 314 "Non-commercial license is non-FOSS"](https://github.com/mariuszgromada/MathParser.org-mXparser/issues/314#issuecomment-1867094454)

> This license is not a FOSS license, it allows the library to be used in FOSS as long as it is for non-commercial use.

> These conditions were introduced less than two years ago. Versions of the library that were available before were based on BSD and can still be used.

**Comment by mariuszgromada** [comment]
Hello. mXparser can be used free of charge by any software that is not intended to make money. If yetCalc is made available for free, i.e. its author/distributor does not earn money from this application, it can use mXparser without restrictions.

**Comment by linsui** [comment]
Hi @mariuszgromada , the problem is that the license of mXparser is not a FOSS license. Though yetCalc can use it without restrictions, F-Droid requires that all libs used by an app in it must be FOSS. yetCalc can use your lib but we can't include it in F-Droid.

**Comment by mariuszgromada** [comment]
@opk12 @linsui @licaon-kter Unfortunately I can't make my license FOSS because then I allow unrestricted commercial use for everyone. For example, I can make an exception for yetCalc so that this application can be available in F-Droid, because yetCalc is non-commercial. However, I have no idea how it should be done. I can, for example, offer you a commercial license for free, but I don't know if it will help.

**Comment by licaon-kter** [comment]
@Yet-Zio fyi https://github.com/sal0max/currencies/commit/c464d3bc906497c2d0ef125d891132c534ff65b4

**Comment by Yet-Zio** [comment]
@licaon-kter Thanks for letting me know. Maybe I will try the same by downgrading mathparser, but also it will take some time to figure out if there are any issues with the app. Once its done, fdroid can accept the app again, am I right?

**Comment by licaon-kter** [comment]
Since that was the only setback, yes

**Comment by Yet-Zio** [comment]
Hello @licaon-kter @linsui I have downgraded to MathParser.org-mXparser:4.4.3 and created a new release 'v1.1.2' as well.
So now the issues are solved I guess?

**Comment by licaon-kter** [comment]
Will test asap :)

**Comment by licaon-kter** [comment]
:tada: https://gitlab.com/fdroid/fdroiddata/-/commit/fe38243d3b28d51710a86fdbc9f791ac1dbf58cf
